### ISSUE TITLE
custom validation error message

### ISSUE THREAD

**Issue by ubourdon** [julienrf/play-json-variants#15]
When send json without $variant type the error message is : List((,List(ValidationError(error.expected.jsstring,WrappedArray()))))

It is not very significant. Can we try to update this message ?

**Comment by julienrf** [comment]
Yes, instead of generating `(json \ "$variant").validate[String]` we could generate code using a custom `Reads[String]` value that would produce a more sensible error message in case of failure. I would be happy to merge a pull request for that.

**Comment by julienrf** [comment]
Fixed by 775615b7aa721440bf586d6a90f8eff3322cf791
